[package]
name = "my_macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "2.0.106", features = ["full"] }
quote = "1"
proc-macro2 = "1"

[lib]
proc-macro = true      # enable procedural macros